version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx
    env_file: .env
    build:
      context: ./requirements/nginx/
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    image: mariadb
    env_file: .env
    build:
      context: ./requirements/mariadb/
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    container_name: wordpress
    image: wordpress
    env_file: .env
    build:
      context: ./requirements/wordpress/
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver_opts:
      type: none
      device: /home/data/mariadb
      o: bind
  wordpress:
    driver_opts:
      type: none
      device: /home/data/wordpress
      o: bind
