version: "3"

services:
  nginx:
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - "443:443"
        #    command: ["sleep", "infinity"]
  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    command: ["sleep", "infinity"]
